server:
  port: 8000

logging:
  file: /home/br/logs/brAdmin

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true


task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/秒
code:
  expiration: 300

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJ0WzMPPfEshDkZkp2s5Xq7jpSSMReBb4rswzH0oDKcdauDLfN5BkJ8yP0pFpmqCaH6tiQ79AQ0G5KsEOWgRnGsZkVWeyM/d+gFadFoIw+2sJHxTylhhloM+cPW6Fz29Sz1UHDUJetXtRXwQPFrfzCvnZMAQqi70yemVBwrSrRT7AgMBAAECgYBuj9OCpZAHmLZhWQp0byZy1QowVQIBTOqhcVEbbYqqPAwzN0UlcOQHB+h/r9HW+P3u2tiyUePhdU6QByMYWfzKUCDILIbH6MPJFals4Lb+xS9zyG3wIajGZy3Jw+aqtF06+FxNnZD2tRGFAEDuQjEcc+EQM2gvMTsq64PBndsMYQJBAOH9cfWEIeqVSDDfKN+cYC/2YPohU0ctJkEh6EnNFDXDlUmxBkUaaZjPQfvv/GSlBEXOK//eoGERGHAG0stuYKkCQQCx8w8tWnSQ7UEm56PbSdrI4Uzj7HuZJY2E4i2bter/SdrqFpyXbe4tizpNc+ePafwJL/3QH82HT2NW2OshIzsDAkBoxAQGm8DVbWtQLMRYFbiJw6BllPl0b7viSgPT4tzRp+AXj5emhX4at0qRr0nEprN6YQAI2H5lQXWgyakDYiIxAkBUkmr1KBdcRZYAUnjaoIgdjo5HiL3ZNDLFI+V/Kn9sIwKq3GJBydo3xQLJirtTupAxIaDkSCkbFMzmmqNtFVxXAkBFMg0bHLHeFidcDUtUr3/dM79WXOhcpvuU8x/0FgIk7IUrpGCyxaPEZ5N+EOwxgzmqEkuxaE0Hv3AXVFm1Mhjd
  public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCdFszDz3xLIQ5GZKdrOV6u46UkjEXgW+K7MMx9KAynHWrgy3zeQZCfMj9KRaZqgmh+rYkO/QENBuSrBDloEZxrGZFVnsjP3foBWnRaCMPtrCR8U8pYYZaDPnD1uhc9vUs9VBw1CXrV7UV8EDxa38wr52TAEKou9MnplQcK0q0U+wIDAQAB